### ISSUE TITLE
optax manifest entry is missing latest_verified_commit in current `jax:mealkit` image

### ISSUE THREAD

**Issue by gspschmid** [NVIDIA/JAX-Toolbox#490]
As of 2024-01-22:
```bash
$ docker run --rm -it --shm-size=1g ghcr.io/nvidia/jax:mealkit grep -A5 'optax:' /opt/manifest.d/manifest.yaml
optax:                                                                                                                                                                                   
  url: https://github.com/deepmind/optax.git                                                                                                                                             
  tracking_ref: master                                                                                                                                                                   
  latest_verified_commit: ""                                                                                                                                                             
  mode: pip-vcs                                                                                                                                                                          
seqio:           
```
The empty entry for `latest_verified_commit` seems fishy and appears to break `pip-finalize.sh` down the road.

The entry seems to be properly populated with commits in date-tagged images (I tried `jax:mealkit-2024-01-19` and `jax:mealkit-2024-01-22`).

@yhtang How is `jax:mealkit` published? Could it be that we manually published a broken image? I wonder if this might be related to @olupton's recent change in https://github.com/NVIDIA/JAX-Toolbox/pull/480/files#diff-dfbf1e0965ac986e3974f64ef32f1a84a941ab6f3a982bd1cbc7ac67d8552ba3R85-R88 ?

---

I ran into this while working on the T5X arm64 Dockerfile -- the missing `latest_verified_commit` ends up breaking `pip-finalize.sh`, in particular the second `pip-compile` run within:
```
+ pip-compile -o requirements.txt requirements.vcs requirements-flax.in requirements-jax.in requirements-t5x.in requirements-te.in                                                       
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>                                    
    sys.exit(cli())                                                                                                                                                                      
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__                                                                                                   
    return self.main(*args, **kwargs)   
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main          
    rv = self.invoke(ctx)                                                                   
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke        
    return ctx.invoke(self.callback, **ctx.params)                                          
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke         
    return __callback(*args, **kwargs)                                                      
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func  
    return f(get_current_context(), *args, **kwargs)                                        
  File "/usr/local/lib/python3.10/dist-packages/piptools/scripts/compile.py", line 659, in cli                                                                                           
    results = resolver.resolve(max_rounds=max_rounds)                                       
  File "/usr/local/lib/python3.10/dist-packages/piptools/resolver.py", line 604, in resolve 
    is_resolved = self._do_resolve(       
  File "/usr/local/lib/python3.10/dist-packages/piptools/resolver.py", line 636, in _do_resolve                                                                                          
    resolver.resolve(                                                                       
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve  
    collected = self.factory.collect_root_requirements(root_reqs)                           
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/factory.py", line 513, in collect_root_requirements                                                                             
    reqs = list(                            
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/factory.py", line 474, in _make_requirements_from_install_req                                                                   
    cand = self._make_candidate_from_link(                                                                                                                                               
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link                                                                             
    self._link_candidate_cache[link] = LinkCandidate(                                       
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__                                                                                           
    super().__init__(                                                                       
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__                                                                                           
    self.dist = self._prepare()
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare                                                                                           
    dist = self._prepare_distribution()                                                     
  File "/opt/pip/src/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution                                                                              
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)            
  File "/opt/pip/src/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement                                                                                       
    return self._prepare_linked_requirement(req, parallel_builds)                                                                                                                        
  File "/opt/pip/src/pip/_internal/operations/prepare.py", line 596, in _prepare_linked_requirement                                                                                      
    local_file = unpack_url(         
  File "/opt/pip/src/pip/_internal/operations/prepare.py", line 157, in unpack_url                                                                                                       
    unpack_vcs_link(link, location, verbosity=verbosity)                                                                                                                                 
  File "/opt/pip/src/pip/_internal/operations/prepare.py", line 80, in unpack_vcs_link
    vcs_backend.unpack(location, url=hide_url(link.url), verbosity=verbosity)                                                                                                            
  File "/opt/pip/src/pip/_internal/vcs/versioncontrol.py", line 608, in unpack              
    self.obtain(location, url=url, verbosity=verbosity)                                                                                                                                  
  File "/opt/pip/src/pip/_internal/vcs/versioncontrol.py", line 518, in obtain              
    url, rev_options = self.get_url_rev_options(url)                                                                                                                                     
  File "/opt/pip/src/pip/_internal/vcs/versioncontrol.py", line 441, in get_url_rev_options                                                                                              
    secret_url, rev, user_pass = self.get_url_rev_and_auth(url.secret)                      
  File "/opt/pip/src/pip/_internal/vcs/git.py", line 482, in get_url_rev_and_auth      
    url, rev, user_pass = super().get_url_rev_and_auth(url)                                 
  File "/opt/pip/src/pip/_internal/vcs/versioncontrol.py", line 419, in get_url_rev_and_auth                                                                                             
    raise InstallationError(                                                                
pip._internal.exceptions.InstallationError: The URL 'git+https://github.com/deepmind/optax@' has an empty revision (after @) which is not supported. Include a revision after @ or remove
 @ from the URL.     
```

**Comment by gspschmid** [comment]
Resolved -- @olupton points out that the most recent image corresponding to `ghcr.io/nvidia/jax:mealkit` is actually fine (provided one has recently `docker pull`-ed...).
